version: "3"

services:
  app:
    container_name: node-api
    build: ./node-api
    env_file:
      - ./node-api/.env
    # ports:
    #   - "3000:3000"
    networks:
      - nginx-com-nodejs
    depends_on:
      - db
      - reverse-proxy
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./node-api/.env
    networks:
      - nginx-com-nodejs
  reverse-proxy:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - nginx-com-nodejs

networks:
  nginx-com-nodejs:
    driver: bridge